In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
AC = pd.read_csv('Airplane_Crashes_and_Fatalities_Since_1908.csv')

In [3]:
AC.head() # AC.Sample(5)

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary
0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,1.0,1.0,1.0,0.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,09/07/1909,NaN,"Juvisy-sur-Orge, France",NaN,NaN,Air show,Wright Byplane,SC1,NaN,1.0,0.0,1.0,1.0,0.0,0.0,0.0,Eugene Lefebvre was the first pilot to ever be...
2,07/12/1912,06:30,"Atlantic City, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,0.0,5.0,5.0,0.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
3,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,NaN,NaN,Curtiss seaplane,NaN,NaN,1.0,0.0,1.0,1.0,0.0,1.0,0.0,The first fatal airplane accident in Canada oc...
4,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,NaN,NaN,14.0,NaN,NaN,0.0,The airship flew into a thunderstorm and encou...

In [4]:
AC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4967 entries, 0 to 4966
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   4967 non-null   object
 1   Time                   3457 non-null   object
 2   Location               4963 non-null   object
 3   Operator               4957 non-null   object
 4   Flight #               1315 non-null   object
 5   Route                  4193 non-null   object
 6   AC Type                4952 non-null   object
 7   Registration           4694 non-null   object
 8   cn/ln                  4299 non-null   object
 9   Aboard                 4949 non-null   float64
 10  Aboard Passangers      4738 non-null   float64
 11  Aboard Crew            4741 non-null   float64
 12  Fatalities             4959 non-null   float64
 13  Fatalities Passangers  4725 non-null   float64
 14  Fatalities Crew        4726 non-null   float64
 15  Ground                 4926 non-null   float64
 16  Summary                4903 non-null   object
dtypes: float64(7), object(10)
memory usage: 659.8+ KB

In [5]:
AC['Route'].value_counts()

Training                      92
Sightseeing                   31
Test flight                   22
Sao Paulo - Rio de Janeiro     7
Test                           6
                              ..
Kokkola - Vaasa                1
New York - Mexico City         1
Survey                         1
Jakarta - Bandung              1
Spokane - Missoula             1
Name: Route, Length: 3800, dtype: int64

In [6]:
AC['Route'] = AC['Route'].replace('Test', 'Test flight')
AC['Route'].value_counts()

Training                                92
Sightseeing                             31
Test flight                             28
Sao Paulo - Rio de Janeiro               7
Rio de Janeiro - Sao Paulo               5
                                        ..
New York - Mexico City                   1
Survey                                   1
Jakarta - Bandung                        1
Kenitra - Lajes - Argentia - Norfork     1
Toledo - Kansas City, MO                 1
Name: Route, Length: 3799, dtype: int64

#### Observation: Here most of the crash happened during Training and Sightseeing, Test flight

In [7]:
AC['Operator'].value_counts()

Aeroflot                                     255
Military - U.S. Air Force                    140
Air France                                    72
Deutsche Lufthansa                            63
United Air Lines                              44
                                            ...
Indonesian Air Force                           1
Russian Air Force                              1
My Cargo Airlines (ACT Airlines)               1
Australian Corporate Jet Centres PTY. LTD      1
Swan Aviation                                  1
Name: Operator, Length: 2242, dtype: int64

In [8]:
AC['Operator'].value_counts().head(20)

Aeroflot                               255
Military - U.S. Air Force              140
Air France                              72
Deutsche Lufthansa                      63
United Air Lines                        44
China National Aviation Corporation     43
Military - U.S. Army Air Forces         43
Pan American World Airways              41
American Airlines                       37
US Aerial Mail Service                  35
Indian Airlines                         34
KLM Royal Dutch Airlines                34
Philippine Air Lines                    33
Military - Royal Air Force              32
Private                                 30
Military - U.S. Navy                    29
British Overseas Airways                29
Military - U.S. Army                    27
Eastern Air Lines                       25
Northwest Orient Airlines               25
Name: Operator, dtype: int64

#### Observation-2: Aeroflot operator flight has most Crashes

In [9]:
AC.sample(5)

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary
4090,09/12/1997,NaN,"Near Uvira, Zaire",TMK Air Commuter,NaN,Buknavu - Uvira,de Havilland Canada DHC-6 Twin Otter 300,9Q-CBO,735,22.0,21.0,1.0,22.0,21.0,1.0,0.0,The aircraft was destroyed when it flew into a...
3334,09/29/1985,12:30,"Jenkinsburg, Georgia",Air Carriers Express Services Inc,NaN,Parachuting,Cessna 208 Caravan I,N551CC,208-00017,17.0,16.0,1.0,17.0,16.0,1.0,0.0,Lost power and spiraled into the ground after ...
4087,08/29/1997,NaN,"Puerto Inirida, Venezuela",SATENA,NaN,San Felipe - Puerto Inirida,Pilatus PC-6 Turbo Porter / Cessna 206,FAC1115,820,12.0,10.0,2.0,12.0,10.0,2.0,0.0,Collided with a Cessna 206 (OB-1450) and crash...
1655,11/15/1957,20:08,"Near Palma de Mallorca, Spain",Aviaco,NaN,Barcelona - Palma de Mallorca,de Havilland DH-114 Heron 2D,EC-ANZ,14117,4.0,2.0,2.0,4.0,2.0,2.0,0.0,"The aircraft hit a mountain at 1,500 feet whil..."
4437,07/13/2003,12:15,"Near San Cristobal, Venezuela",Ruiban & Duran Compania Aérea,NaN,La Carlota - San Cristobal,Let 410UVP-E,YV-1060CP,902505,10.0,8.0,2.0,4.0,4.0,0.0,0.0,Crashed atop a hill in Chorro del Indio Nation...

In [10]:
AC['Date'].str[-4:]

0       1908
1       1909
2       1912
3       1913
4       1913
        ...
4962    2019
4963    2019
4964    2019
4965    2019
4966    2019
Name: Date, Length: 4967, dtype: object

In [11]:
AC['Year'] = AC['Date'].str[-4:]

In [12]:
AC.sample(4)

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary,Year
4101,12/13/1997,17:05,"La Veriente, Bolivia",STAP,NaN,Villamontes - Santa Cruz,Swearingen SA-226T Metro II,CP-1635,TC-359,19.0,17.0,2.0,10.0,9.0,1.0,0.0,"During take off, shortly after the landing gea...",1997
1579,09/09/1956,14:32,"Bartlesville, Oklahoma",Continental Airlines,190,Tulsa - Bartlesville,Douglas DC-3 / Cessna 170B,N33315 / N8143A,4978 / 20995,18.0,14.0,4.0,0.0,0.0,0.0,0.0,Midair collision. Both planes landed safely. F...,1956
105,11/14/1925,NaN,"Nouadhibou, Mauritania",Lignes Aeriennes Latecoere,NaN,NaN,Breguet 14,F-AEGZ,168,1.0,0.0,1.0,1.0,0.0,1.0,0.0,The pilot suffered sunstroke lost control of t...,1925
3502,10/17/1988,00:30,"Rome, Italy",Uganda Airlines,775,London - Rome,Boeing B-707-338C,5X-UBC,19630/746,52.0,45.0,7.0,33.0,26.0,7.0,0.0,Undershot runway and hit a building while per...,1988

In [13]:
AC['month'] = AC['Date'].str[:2] # Month

In [14]:
AC.sample(3)

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary,Year,month
1002,12/18/1947,09:30,"Krasnoyarsk, Russia",Aeroflot,6,Krasnoyarsk - Omsk,Ilyushin IL-12,CCCP-L1343,30 049,25.0,20.0,5.0,9.0,3.0,4.0,0.0,Crash landed due to engine failure after an at...,1947,12
4161,11/21/1998,17:43,"Edgewater, Maryland",Private,NaN,"Brunswick, GA - Annapolis, MD",Burgess RV-6 experimental,N956DB,21119,1.0,0.0,1.0,1.0,0.0,1.0,0.0,The homebuilt plane was attempting to land at ...,1998,11
2264,04/27/1967,17:10,"Malaybalay, Philippines",Pelita Air Service,NaN,Demonstration,Fokker F-27 Friendship 400,PK-PFB,10306,21.0,18.0,3.0,19.0,16.0,3.0,0.0,The plane crashed at the west end of of the ru...,1967,04