In [90]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [91]:
df = pd.read_csv('moviereviews.csv')

In [92]:
df.head()

  label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   2000 non-null   object
 1   review  1965 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB

In [94]:
df['label'].value_counts()

label
neg    1000
pos    1000
Name: count, dtype: int64

In [95]:
print(df['review'][1])

some talented actresses are blessed with a demonstrated wide acting range while others , almost as gifted , have more limited types of parts for which they are suitable .
as was amply evident after basic instinct , sharon stone can play sensual roles with great abandon .
rejecting her natural abilities , she has spent the rest of her entire career trying with little success to play against type .
gloria is her latest disaster .
babe ruth didn't quit baseball after one season to play football in a quixotic quest to prove his athletic dexterity , and neither should stone reject what she does best .
janeane garofalo , for example , is no less wonderful an actress because she could have never pulled off stone's part in basic instinct ; neither is stone any less talented because she couldn't do garofalo's comedic roles .
gloria , directed by respected director sidney lumet and adapted by steve antin from the 1980 screenplay by john cassavetes , was not screened in advance for critics , almost always a sign that the studio isn't behind the picture .
after seeing it in a nearly empty audience after it opened , it is clear why they held it from the press .
it is a film more to be endured than enjoyed .
as the story opens , an angry gloria ( stone ) is being released from prison after 3 years confinement .
she's got a bad attitude and a big mouth .
she also has a bad case of wavering and overblown new york accents , a disease suffered by much of the rest of the cast .
an annoying child actor named jean-luke figueroa plays a soon-to-be orphan named nicky .
just before his whole family is gunned down by hoods working for gloria's ex-boyfriend kevin ( jeremy northam ) , nicky's dad gives him a banana yellow floppy disk with secrets about kevin's operation and offers him a piece of fatherly advice .
 " be a man , " his father lectures him sternly .
 " don't trust nobody .
not no broads .
nobody . "
most of the film's leaden dialog is delivered with the emotive power of the automated time and temperature announcements .
add in the movie's almost non-existent background noise and the excruciatingly slow pacing , and you can hear the sounds of the lines falling to the ground like stones .
lumet places his actors in the frames like fruit in a still life painting .
they stand awkwardly mouthing the stiff sentences that pass for discourse .
 ( " say you're my baby , " kevin coos demandingly .
 " i'm not gonna , " gloria pouts back . )
the movie has a plethora of logical flaws and implausibilites .
the kid rarely seems the least bit worried or scared , no matter how many people are after him with guns , trying to kill him .
and in one key scene , the yellow floppy he holds is assumed to be the right disk without checking it and is further assumed never to have been copied .
gloria , who keeps saying how she hates kids , takes nicky under her wing and protects him from kevin and the bad guys .
think her maternal instincts will show up before the movie finally and predictably ends ?
if you don't know the answer , you may be just the right viewer for this film .
you have to say this for stone : she can keep a straight face .
when explaining life to a 7-year-old kid , she says with utter seriousness , " you got a lot of love making to make ; you got a lot of boozing to do . "
gloria runs 1 : 48 .
it is rated r for profanity , violence and brief male nudity and would be acceptable for teenagers .

In [96]:
df.isnull().sum()

label      0
review    35
dtype: int64

In [97]:
df = df.dropna()

In [98]:
df['review'].value_counts()

review
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              27
for more than a decade , anjelica huston has been one of america's finest actresses . \r\nin her directorial debut , bastard out of carolina , based upon dorothy allison's largely autobiographical book on child abuse and poverty in the south , huston displays impressive proficiency behind the camera as well . \r\nthe film tells the story of ruth anne boatwright , nicknamed bone by one of her uncles at birth , in post-world war ii south carolina . \r\nthrough voice-over ( narration done by laura dern ) , we find that she nearly didn't survive birth , as her single mother anney , played by jennifer jason leigh , was thrown through the windshield during an automobile accident . \r\nthat's just the beginning of her troubles . \r\nbone is deemed illegitimate on her birth certificate , a social stigma which her mother and her large poor family obsesses over for years to come . \r\nanney meets and weds lyle , a kind man and good stepfather whom gives bone a baby sister before dying in an automobile accident . \r\nanney's brother earle , played by michael rooker , introduces her to glen , played by ron eldard , a co-worker at the mill . \r\nglen , the black sheep of a wealthy family ( " when are you gonna make your daddy proud ? \r\ni'll tell you when - never ! " \r\nhe's told ) and filled with bitterness , courts anney and eventually wins her , despite warnings of a violent temper . \r\nwhen anney miscarries with his much-prized baby boy , glen loses his capability to supress his violent outbursts and begins to direct them at bone , beating and abusing her , while the love-dependent anney tries to turn a blind eye and justify his behaviour . \r\nthings turn for the worse when glen loses his job and the family of four sink into impoverishment . \r\nwhile set several decades ago , this story remains completely relevant in today's society , where abused wives return to their husbands , and abuse committed against children by one spouse is routinely overlooked by the other . \r\nthe real star of this domestic drama is not top-billed jennifer jason leigh , but child actress jena malone , who plays bone in a wrenching and wholly impressive debut performance . \r\nher work is of award-calibre , and in this age in which a preponderence of superb child performers have emerged ( kirsten dunst , tina majorino , anna paquin , natalie portman , christina ricci , elijah wood ) , malone's performance stands up well . \r\nleigh's performance in bastard out of carolina is fine , although she's not really given much to do , and ron eldard work is very solid , skillfully manouvering his character's moods in and out of explosive rage . \r\none can always sense that underneath his glen is a pressure-cooker ticking away . \r\nof the supporting cast , special note must be made of the criminally underrated michael rooker's performance . \r\nthere's a bit too much generic formulaism in the screenplay for my taste , from the various characters spouting off country bumpkinisms , to the familiar sight of a dried-up uptight wise old granny ( played by grace zabriskie ) sitting on the porch rocking chair , to impassioned soliloquies better suited for a stage performance . \r\nstill , it cannot be denied that anne meredith's screenplay contains a wallop of emotional power . \r\nhuston's direction of the film is surehanded and impressive , giving the film good pacing and eliciting good performances from her cast , particularly the young malone . \r\nher sequences of child abuse are shot in a hard-hitting emotional , rather than graphic , manner , and are very effective . \r\nhuston's talent with camera positioning is wonderful , from a visually striking shot done through a fan , to an extended sequence in the front seat of an automobile . \r\nthe film has the toned-down feel of a television production ; bastard out of carolina was originally composed and cut for broadcast on the tnt cable station , who ended up declining the film due to sentiments that scenes of abuse and rape in the film were too disturbingly realistic for their audience . \r\nperhaps some sequences of the film may be unpleasant , but as a whole bastard out of carolina adds up to a powerful viewer experience worth seeing . \r\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1
 " love is the devil " is a challenging film , munundating its audience with wild imagery and a plot structure that disallows a plot , perhaps in an attempt to get us to know the artist's psyche rather than the artist's lifeline . \r\nwatching it , i was enthralled with the look of the film , the way the director shot everything like it was looking through a bizarre , personalized filter . \r\neverything looks like it is not how life looks like but how painter francis bacon , the film's subject , looked at it personally . \r\nbut while i was engrossed , i stumbled upon my thoughts halfway through the film , awakened from my trance by some inner distraction , and began to try and follow what's going on . \r\nexactly what was i looking at ? \r\nwatching this film , i wasn't sure if it was the most insightful film i had ever seen or the most vacuous . \r\ndirected ( and written ) by john maybury , " love is the devil " is stylish masterpiece for the senses . \r\neverything looks originally bizarre and perplexing . \r\nthe camera angles are ferociously askew , and the close-ups are uncomfortably too close . \r\nthe editing is deft , occasionally cutting away to something bizarre every couple seconds , but other times holding on a shot for so long that you wonder if the audience is not supposed to be voyeurs , or rather , intruders to bacon's world and psyche . \r\nas such , there is no real story . \r\ni've not heard much about francis bacon that i didn't read prior to the film , but what i learned was this : he was a painter in england who reached his peak during the 60s and 70s , drawing hideously bizarre drawings of carnage and the like . \r\nhe was one of the first to really come out of the closet , and in interviews , he was notoriously drunk yet incredibly witty . \r\nas played by great shakesperean actor derek jacobi , he's like a foppish and self-absorbed cross between oscar wilde and nero . \r\nhe lives life the way he wants to live it , to the disatisfaction of those who have the privelege of being really close to him . \r\nit's as if he were taking delight in the destruction of others and maybe himself ( " champagne for my real friends , and pain for my sham friends , " he says one night at the bar he frequents ) . \r\n " love is the devil " chronicles the latter part of his life . \r\nbacon , well-known in his mid-life , awakens one night when he hears a man tumble through his ceiling window and land on the floor . \r\nhe walks in , unafraid of what he finds , and discovers a thief , george dyer ( daniel craig ) . \r\nbacon gives him an offer : if he spends the night with him , he can take anything he wants in the morning . \r\ngeorge agrees to this , and off to bed he goes , but ends up staying with him , for whatever reason . \r\nthe film shows their lives together , at least in reference to one another . \r\nwhile creating bacon's world of friends ( like " high art , " this film minors in showing a certain group of people who radiate a connection that is not shown but is understood ) , the film shows the relationship of bacon and george as it remains rather stagnant . \r\nbacon is haughty and bizarre ; george is simple and doesn't understand bacon in the least , especially not his paintings . \r\nwhile watching this , that's basically all i thought was there . \r\nthe film has a hypnotic feel , free of any restraints of form , and is shot so uniquely that i felt my attention was almost entirely on the way this film was made rather than what it is about . \r\nonce the film is over , it's easier to piece it together . \r\ni kept on thinking about this film , wondering what the point to all of it was . \r\nsomeone doesn't merely make a film of all style and no substance at all , and if they do , they do it by accident , but still allow some substance to creep in . \r\nthinking about it , i remembered how the two fed off of eachother . \r\ni thought about how bacon was a masochist , in love with cruelty ( in one scene , he watches a boxing match with a orgiastic delight , and lets out a squeal of pleasure when blood from the one boxer's head splashes across his face ; in another scene , he masturbates to the odessa steps sequence of eisenstein's " battleship potemkin " ) , and perhaps he drove george too far in his delight for pain . \r\nhe drove him over the edge , and for him that was love , even if it wasn't for george . \r\ni guess that explains the title . \r\na bit . \r\nthat's great and all , but i almost wish the film was devoid of any meaning . \r\ni wish it hadn't reduced itself to making some point about humanity , about how love is the most selfish thing in the world ( and it is , if you look at it a certain way ) . \r\nor maybe if it had avoided any meaning about humanity and merely drove itself into being the one film that was truly inside one man's twisted pysche . \r\nit's almost always best to obtain insights from looking at one man's uniqueness than it is forcing universality down an audience's throat . \r\nthat way you don't reduce your film to something it's just not . \r\ni can't say i totally enjoyed " love is the devil , " though . \r\ndespite all of the things i respect about this movie , it's still rather uncomfortable to sit through . \r\neven at a normally trite length of ninety minutes , the film still seems like an arduous task to sit through , especially after an exhausting first hour . \r\nthough hypnotic , it still almost seems gimmicky and even redundant at times , as if it were taking advantage of one man's truly bizarre nature but not doing anything deeper with it . \r\nas such , i respect the way the film looks . \r\nit's beautiful and painstakingly crafted so that , along with " what dreams may come " and " dark city , " it's the year's most visually stunning film . \r\nin fact , if a better script had been forged , i'd almost compare it in visual power to a peter greenaway film , complete with similar haunting images that stick in the mind forever . \r\nand with a dymanite performance by derek jacobi , it has the comic and distanced tone that it needs . \r\ni just wish it had been more than mostly style and just a hair bit of substance . \r\nthen i would have had something to hold me over even now . \r\n     1

In [99]:
df[df['review'] == '  ']

     label review
57     neg
71     pos
147    pos
151    pos
283    pos
307    pos
313    neg
323    pos
343    pos
351    neg
427    pos
501    neg
633    pos
675    neg
815    neg
851    neg
977    neg
1079   neg
1299   pos
1455   neg
1493   pos
1525   neg
1531   neg
1763   neg
1851   neg
1905   pos
1993   pos

In [100]:
df['review'].str.isspace()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Name: review, Length: 1965, dtype: bool

In [101]:
df[df['review'].str.isspace()]

     label review
57     neg
71     pos
147    pos
151    pos
283    pos
307    pos
313    neg
323    pos
343    pos
351    neg
427    pos
501    neg
633    pos
675    neg
815    neg
851    neg
977    neg
1079   neg
1299   pos
1455   neg
1493   pos
1525   neg
1531   neg
1763   neg
1851   neg
1905   pos
1993   pos

In [102]:
df = df[~df['review'].str.isspace()]

In [103]:
df['label'].value_counts()

label
neg    969
pos    969
Name: count, dtype: int64

### Exploration on bag of words: 
* trying to see the common words in positive and negative reviews.

In [104]:
from sklearn.feature_extraction.text import CountVectorizer

In [105]:
cv = CountVectorizer(stop_words='english')

In [106]:
matrix = cv.fit_transform(df[df['label'] == 'neg']['review'])
freq = list(zip(cv.get_feature_names_out(),matrix.sum(axis = 0).tolist()[0]))
print("Top 20 repetative words in Negative reviews.")
sorted(freq, key = lambda x:-x[1])[:20]

Top 20 repetative words in Negative reviews.

[('film', 4063),
 ('movie', 3131),
 ('like', 1808),
 ('just', 1480),
 ('time', 1127),
 ('good', 1117),
 ('bad', 997),
 ('character', 926),
 ('story', 908),
 ('plot', 888),
 ('characters', 838),
 ('make', 813),
 ('really', 743),
 ('way', 734),
 ('little', 696),
 ('don', 683),
 ('does', 666),
 ('doesn', 648),
 ('action', 635),
 ('scene', 634)]

In [107]:
matrix = cv.fit_transform(df[df['label'] == 'pos']['review'])
freq = list(zip(cv.get_feature_names_out(),matrix.sum(axis = 0).tolist()[0]))
print("Top 20 repetative words in Postive reviews.")
sorted(freq, key = lambda x:-x[1])[:20]

Top 20 repetative words in Postive reviews.

[('film', 5002),
 ('movie', 2389),
 ('like', 1721),
 ('just', 1273),
 ('story', 1199),
 ('good', 1193),
 ('time', 1175),
 ('character', 1037),
 ('life', 1032),
 ('characters', 957),
 ('way', 864),
 ('films', 851),
 ('does', 828),
 ('best', 788),
 ('people', 769),
 ('make', 764),
 ('little', 751),
 ('really', 731),
 ('man', 728),
 ('new', 702)]

### Training and Prediction:

In [108]:
from sklearn.model_selection import train_test_split

X = df['review']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=50)

In [109]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC

In [110]:
pipe = Pipeline([('tfidf', TfidfVectorizer()),('svc',LinearSVC())])

In [111]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('svc', LinearSVC())])

In [112]:
from sklearn.metrics import classification_report, confusion_matrix

In [113]:
pred = pipe.predict(X_test)

In [114]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

         neg       0.89      0.80      0.84       205
         pos       0.79      0.89      0.84       183

    accuracy                           0.84       388
   macro avg       0.84      0.84      0.84       388
weighted avg       0.84      0.84      0.84       388

In [115]:
confusion_matrix(pred, y_test)

array([[163,  21],
       [ 42, 162]])

### Final training with entire data available:

In [116]:
pipe.fit(df['review'], df['label'])

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('svc', LinearSVC())])

In [119]:
new_review = ['Nice movie. Great acting and writing.']
pipe.predict(new_review)

array(['pos'], dtype=object)

In [120]:
new_review = ['Nice movie. Great acting.']
pipe.predict(new_review)

array(['neg'], dtype=object)

In [121]:
new_review = ["Pawan Kalyan's latest film, OG, is a refreshing and captivating experience that stands out from the usual fare. The film’s greatest strength lies in its bold and experimental approach to filmmaking, a welcome change that shows a dedication to pushing cinematic boundaries. The director's vision is evident in every frame, creating a stylish and immersive world that pulls the audience in from the very first scene."]
pipe.predict(new_review)

array(['pos'], dtype=object)

In [122]:
new_review = ["The worst and the very worst film in the universe if you ask me. Zero zip nada cocept and the worst acting I've ever seen. Congrats Mr.Vijay I hope you encounter more ironies like you are a good actor"]
pipe.predict(new_review)

array(['neg'], dtype=object)